site_name: Bedrock Configurator

theme:
  - name: mkdocs
  - color_mode: auto
  - user_color_mode_toggle: true

markdown_extensions:
  - abbr

repo_url: https://github.com/mozmeao/www-config
edit_uri: ""
